const {DatabaseSync}=require('node:sqlite');
const {randomBytes,createHash,scrypt,timingSafeEqual}=require('node:crypto');
const {promisify}=require('node:util');
const fs=require('node:fs');const path=require('node:path');
const derive=promisify(scrypt);const hash=s=>createHash('sha256').update(s).digest('hex');
const token=()=>randomBytes(32).toString('hex');
const fail=(message,status=400)=>{throw Object.assign(new Error(message),{status});};
const text=(v,max=300)=>typeof v==='string'?v.trim().slice(0,max):'';
const integer=(v,min=0,max=100000000)=>Number.isSafeInteger(v)&&v>=min&&v<=max;
const email=v=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v);
async function passwordHash(p){const salt=randomBytes(16).toString('hex');return salt+':'+(await derive(p,salt,64,{N:32768,maxmem:64*1024*1024})).toString('hex');}
async function passwordCheck(p,h){const [salt,digest]=h.split(':');const key=await derive(p,salt,64,{N:32768,maxmem:64*1024*1024});return timingSafeEqual(Buffer.from(digest,'hex'),key);}
function createBackend(options={}){
 const dataDir=options.dataDir||process.env.DATA_DIR||path.join(__dirname,'data');
 const production=options.production??process.env.NODE_ENV==='production';
 if(production&&(!process.env.DATA_DIR||!process.env.RAILWAY_VOLUME_MOUNT_PATH))throw Error('Persistent volume is required in production');
 fs.mkdirSync(dataDir,{recursive:true});const db=new DatabaseSync(path.join(dataDir,'commerce.sqlite'));db.exec('PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;');
 db.exec(`CREATE TABLE IF NOT EXISTS categories(id TEXT PRIMARY KEY,name TEXT NOT NULL,image TEXT NOT NULL DEFAULT '');
 CREATE TABLE IF NOT EXISTS products(id TEXT PRIMARY KEY,sku TEXT NOT NULL UNIQUE,name TEXT NOT NULL,category_id TEXT NOT NULL REFERENCES categories(id),description TEXT NOT NULL DEFAULT '',image TEXT NOT NULL DEFAULT '',price INTEGER,stock INTEGER,active INTEGER NOT NULL DEFAULT 1,version INTEGER NOT NULL DEFAULT 1,updated_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS admins(email TEXT PRIMARY KEY,password_hash TEXT NOT NULL,created_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS sessions(hash TEXT PRIMARY KEY,email TEXT NOT NULL REFERENCES admins(email),csrf TEXT NOT NULL,expires INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS quotes(id TEXT PRIMARY KEY,token_hash TEXT NOT NULL UNIQUE,request_key TEXT NOT NULL UNIQUE,customer TEXT NOT NULL,company TEXT NOT NULL,email TEXT NOT NULL,phone TEXT NOT NULL,address TEXT NOT NULL,note TEXT NOT NULL,items TEXT NOT NULL,status TEXT NOT NULL,shipping INTEGER NOT NULL DEFAULT 0,valid_until TEXT,admin_note TEXT NOT NULL DEFAULT '',tracking TEXT NOT NULL DEFAULT '',carrier TEXT NOT NULL DEFAULT '',version INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS events(id INTEGER PRIMARY KEY AUTOINCREMENT,actor TEXT NOT NULL,action TEXT NOT NULL,resource TEXT NOT NULL,created_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);`);
 if(!db.prepare('PRAGMA table_info(products)').all().some(column=>column.name==='popular'))db.exec('ALTER TABLE products ADD COLUMN popular INTEGER NOT NULL DEFAULT 0 CHECK(popular IN (0,1))');
 const now=()=>new Date().toISOString();
 const q=(sql,...args)=>db.prepare(sql).get(...args),all=(sql,...args)=>db.prepare(sql).all(...args),run=(sql,...args)=>db.prepare(sql).run(...args);
 function transaction(fn){db.exec('BEGIN IMMEDIATE');try{const r=fn();db.exec('COMMIT');return r;}catch(e){db.exec('ROLLBACK');throw e;}}
 const audit=(actor,action,resource)=>run('INSERT INTO events(actor,action,resource,created_at) VALUES(?,?,?,?)',actor,action,resource,now());
 if(!q("SELECT 1 FROM settings WHERE key='seed-v1'")){transaction(()=>{const raw=fs.readFileSync(path.join(__dirname,'public/site-data.js'),'utf8');const data=JSON.parse(raw.slice(raw.indexOf('{'),raw.lastIndexOf('}')+1));for(const c of data.categories)run('INSERT OR IGNORE INTO categories(id,name,image) VALUES(?,?,?)',c.slug,c.name,c.image);run('INSERT OR IGNORE INTO products(id,sku,name,category_id,description,image,price,stock,updated_at) VALUES(?,?,?,?,?,?,?,?,?)','suction-pad-10c-1n','10C-1N','Suction Pad 10C-1N','suction-pad','ลูกยางดูดจับชิ้นงาน ขนาด 10 มม. สูง 12 มม. สอบถามราคาและระยะเวลาจัดส่งก่อนสั่งซื้อ','https://bbioplast.com/wp-content/uploads/2023/09/10c-1N.jpg',null,null,now());run("INSERT INTO settings(key,value) VALUES('seed-v1','1')");});}
 const adminEmail=(options.adminEmail||process.env.ADMIN_EMAIL||'bbioplast@gmail.com').toLowerCase();
 const bootstrapHash=options.bootstrapHash||process.env.ADMIN_SETUP_HASH||'';
 const bootstrapExpires=Number(options.bootstrapExpires||process.env.ADMIN_SETUP_EXPIRES||0);
 const limits=new Map();
 function rate(req,key,max=30){const ip=req.socket.remoteAddress||'unknown';const k=key+':'+ip;const t=Date.now();let item=limits.get(k);if(!item||t>item.until)item={count:0,until:t+600000};item.count++;limits.set(k,item);if(limits.size>10000){for(const [k,v]of limits)if(v.until<t)limits.delete(k);}if(item.count>max)fail('คำขอมากเกินไป กรุณาลองใหม่ใน 10 นาที',429);}
 function send(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer'});res.end(JSON.stringify(data));}
 async function body(req){if(!(req.headers['content-type']||'').startsWith('application/json'))fail('ต้องส่งข้อมูลแบบ JSON',415);let b='';for await(const chunk of req){b+=chunk;if(Buffer.byteLength(b)>150000)fail('ข้อมูลมีขนาดใหญ่เกินไป',413);}try{return JSON.parse(b||'{}');}catch{fail('ข้อมูลไม่ถูกต้อง');}}
 function session(req){const cookies=(req.headers.cookie||'').split(';').map(v=>v.trim());const raw=cookies.find(v=>v.startsWith('bb_session='))?.slice(11);if(!raw)return null;return q('SELECT * FROM sessions WHERE hash=? AND expires>?',hash(raw),Date.now());}
 function auth(req){const s=session(req);if(!s)fail('กรุณาเข้าสู่ระบบ',401);if(!['GET','HEAD'].includes(req.method)&&req.headers['x-csrf-token']!==s.csrf)fail('กรุณารีเฟรชหน้าแล้วลองใหม่',403);return s;}
 function cookie(res,value,maxAge){res.setHeader('Set-Cookie',`bb_session=${value}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${maxAge}${production?'; Secure':''}`);}
 const serialize=row=>{if(!row)return null;const {token_hash,request_key,...safe}=row;safe.items=JSON.parse(row.items);safe.total=safe.items.some(i=>i.unitPrice===null)?null:safe.items.reduce((n,i)=>n+i.qty*i.unitPrice,0)+safe.shipping;return safe;};
 const product=row=>({...row,active:!!row.active,popular:!!row.popular});
 function validateProduct(b){const p={sku:text(b.sku,80),name:text(b.name,160),category_id:text(b.category_id,100),description:text(b.description,5000),image:text(b.image,1500),price:b.price??null,stock:b.stock??null,active:b.active===true?1:0,popular:b.popular===true?1:0};if(!p.sku||!p.name||!q('SELECT 1 FROM categories WHERE id=?',p.category_id))fail('กรุณาระบุ SKU ชื่อ และหมวดสินค้าให้ครบ');if(p.price!==null&&!integer(p.price))fail('ราคาไม่ถูกต้อง');if(p.stock!==null&&!integer(p.stock,0,1000000))fail('สต็อกไม่ถูกต้อง');if(p.image&&!/^https:\/\/[^\s]+$/i.test(p.image))fail('ลิงก์รูปภาพต้องเริ่มด้วย https://');return p;}
 async function handle(req,res,url){if(!url.pathname.startsWith('/api/'))return false;
 try{
 const p=url.pathname,m=req.method;
 if(!['GET','HEAD'].includes(m)){const origin=req.headers.origin;const allowed=options.origin||process.env.PUBLIC_ORIGIN||`http://${req.headers.host}`;if(origin!==allowed||req.headers['x-requested-with']!=='BBWeb')fail('คำขอจากเว็บไซต์อื่นไม่ได้รับอนุญาต',403);}
 if(p==='/api/catalog'&&m==='GET'){send(res,200,{categories:all('SELECT * FROM categories ORDER BY name'),products:all('SELECT * FROM products WHERE active=1 ORDER BY name').map(product)});return true;}
 if(p==='/api/auth/status'&&m==='GET'){const s=session(req);send(res,200,{setupRequired:!q('SELECT 1 FROM admins'),email:s?.email||null,csrf:s?.csrf||null});return true;}
 if(p==='/api/auth/setup'&&m==='POST'){
  rate(req,'auth',10);const b=await body(req);if(q('SELECT 1 FROM admins'))fail('ตั้งค่าผู้ดูแลแล้ว',409);
  if(!bootstrapHash||Date.now()>bootstrapExpires||hash(text(b.token,200))!==bootstrapHash)fail('ลิงก์ตั้งค่าไม่ถูกต้องหรือหมดอายุ',403);
  if(text(b.email,254).toLowerCase()!==adminEmail)fail('อีเมลไม่ตรงกับผู้ดูแลที่กำหนด',403);
  if(typeof b.password!=='string'||b.password.length<12||b.password.length>128)fail('รหัสผ่านต้องมี 12–128 ตัวอักษร');
  const digest=await passwordHash(b.password);transaction(()=>{if(q('SELECT 1 FROM admins'))fail('ตั้งค่าแล้ว',409);run('INSERT INTO admins VALUES(?,?,?)',adminEmail,digest,now());audit(adminEmail,'admin.setup','admin');});send(res,201,{ok:true});return true;
 }
 if(p==='/api/auth/login'&&m==='POST'){rate(req,'auth',15);const b=await body(req);const a=q('SELECT * FROM admins WHERE email=?',text(b.email,254).toLowerCase());if(!a||typeof b.password!=='string'||b.password.length>128||!await passwordCheck(b.password,a.password_hash))fail('อีเมลหรือรหัสผ่านไม่ถูกต้อง',401);const raw=token(),csrf=token();run('DELETE FROM sessions WHERE expires<?',Date.now());run('INSERT INTO sessions VALUES(?,?,?,?)',hash(raw),a.email,csrf,Date.now()+8*3600000);cookie(res,raw,8*3600);send(res,200,{email:a.email,csrf});return true;}
 if(p==='/api/auth/logout'&&m==='POST'){const s=auth(req);run('DELETE FROM sessions WHERE hash=?',s.hash);cookie(res,'',0);send(res,200,{ok:true});return true;}
 if(p==='/api/auth/password'&&m==='POST'){const s=auth(req);rate(req,'password',10);const b=await body(req);const a=q('SELECT * FROM admins WHERE email=?',s.email);if(typeof b.current!=='string'||b.current.length>128||!await passwordCheck(b.current,a.password_hash))fail('รหัสผ่านปัจจุบันไม่ถูกต้อง',403);if(typeof b.password!=='string'||b.password.length<12||b.password.length>128)fail('รหัสผ่านต้องมี 12–128 ตัวอักษร');const digest=await passwordHash(b.password);transaction(()=>{run('UPDATE admins SET password_hash=? WHERE email=?',digest,s.email);run('DELETE FROM sessions WHERE email=?',s.email);audit(s.email,'admin.password','admin');});cookie(res,'',0);send(res,200,{ok:true});return true;}
 if(p==='/api/quotes'&&m==='POST'){
  rate(req,'quote',30);const b=await body(req);if(b.website)fail('คำขอไม่ถูกต้อง');if(!/^[a-zA-Z0-9-]{16,80}$/.test(b.requestKey||''))fail('รหัสคำขอไม่ถูกต้อง');
  if(!/^[a-f0-9]{64}$/.test(b.trackingToken||''))fail('รหัสติดตามไม่ถูกต้อง'); const prior=q('SELECT id,token_hash FROM quotes WHERE request_key=?',b.requestKey);if(prior){if(prior.token_hash!==hash(b.trackingToken))fail('คำขอซ้ำ',409);send(res,200,{id:prior.id,token:b.trackingToken});return true;}
  const customer=text(b.customer,120),company=text(b.company,160),em=text(b.email,254),phone=text(b.phone,40),address=text(b.address,1200),note=text(b.note,3000);
  if(!customer||!email(em)||phone.length<8||!address)fail('กรุณากรอกชื่อ อีเมล เบอร์โทร และที่อยู่ให้ครบ');if(!Array.isArray(b.items)||b.items.length<1||b.items.length>50)fail('กรุณาเลือกสินค้า 1–50 รายการ');
  const items=b.items.map(i=>{if(!integer(i.qty,1,10000))fail('จำนวนสินค้าไม่ถูกต้อง');const item=i.productId?q('SELECT * FROM products WHERE id=? AND active=1',text(i.productId,100)):null;if(i.productId&&!item)fail('สินค้าไม่พร้อมให้สอบถาม');const name=item?.name||text(i.name,200);if(!name)fail('กรุณาระบุสินค้า');return {productId:item?.id||null,sku:item?.sku||'',name,qty:i.qty,unitPrice:null};});
  const id='BB-'+new Date().toISOString().slice(0,10).replaceAll('-','')+'-'+randomBytes(3).toString('hex').toUpperCase();const raw=b.trackingToken;run('INSERT INTO quotes(id,token_hash,request_key,customer,company,email,phone,address,note,items,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)',id,hash(raw),b.requestKey,customer,company,em,phone,address,note,JSON.stringify(items),'pending',now(),now());audit('customer','quote.created',id);send(res,201,{id,token:raw});return true;
 }
 const publicMatch=p.match(/^\/api\/quote\/([a-f0-9]{64})(?:\/(accept))?$/);
 if(publicMatch){rate(req,'track',100);const row=q('SELECT * FROM quotes WHERE token_hash=?',hash(publicMatch[1]));if(!row)fail('ไม่พบรายการ',404);if(m==='GET'&&!publicMatch[2]){send(res,200,serialize(row));return true;}if(m==='POST'&&publicMatch[2]==='accept'){const b=await body(req);const result=transaction(()=>{const r=q('SELECT * FROM quotes WHERE id=?',row.id);if(r.status!=='offered'||r.version!==b.version)fail('ใบเสนอราคามีการเปลี่ยนแปลง กรุณารีเฟรช',409);if(!r.valid_until||Date.now()>Date.parse(r.valid_until))fail('ใบเสนอราคาหมดอายุ กรุณาติดต่อทีมงาน',409);const items=JSON.parse(r.items);for(const i of items){if(!integer(i.unitPrice))fail('ยังไม่ได้กำหนดราคาครบ');if(i.productId){const item=q('SELECT * FROM products WHERE id=?',i.productId);if(!item||!item.active)fail('สินค้าบางรายการไม่พร้อมจำหน่าย',409);if(item.stock!==null){i.reserved=true;if(item.stock<i.qty)fail('สินค้าในสต็อกไม่เพียงพอ กรุณาติดต่อทีมงาน',409);run('UPDATE products SET stock=stock-?,version=version+1,updated_at=? WHERE id=?',i.qty,now(),i.productId);}}}run("UPDATE quotes SET items=?,status='confirmed',version=version+1,updated_at=? WHERE id=?",JSON.stringify(items),now(),r.id);audit('customer','order.confirmed',r.id);return serialize(q('SELECT * FROM quotes WHERE id=?',r.id));});send(res,200,result);return true;}}
 if(p.startsWith('/api/admin/')){
  const s=auth(req);
  if(p==='/api/admin/dashboard'&&m==='GET'){send(res,200,{products:q('SELECT COUNT(*) AS n FROM products').n,pending:q("SELECT COUNT(*) AS n FROM quotes WHERE status='pending'").n,offered:q("SELECT COUNT(*) AS n FROM quotes WHERE status='offered'").n,orders:q("SELECT COUNT(*) AS n FROM quotes WHERE status IN ('confirmed','processing','shipped','completed')").n,lowStock:all('SELECT id,name,stock FROM products WHERE active=1 AND stock IS NOT NULL AND stock<=5'),events:all('SELECT * FROM events ORDER BY id DESC LIMIT 20')});return true;}
  if(p==='/api/admin/catalog'&&m==='GET'){send(res,200,{categories:all('SELECT * FROM categories ORDER BY name'),products:all('SELECT * FROM products ORDER BY updated_at DESC').map(product)});return true;}
  if(p==='/api/admin/categories'&&m==='POST'){const b=await body(req);const name=text(b.name,120);if(!name)fail('ระบุชื่อหมวดสินค้า');const id='cat-'+randomBytes(6).toString('hex');run('INSERT INTO categories(id,name) VALUES(?,?)',id,name);audit(s.email,'category.created',id);send(res,201,{id});return true;}
  const cm=p.match(/^\/api\/admin\/categories\/([a-zA-Z0-9-]+)$/);if(cm&&m==='PUT'){const b=await body(req);const name=text(b.name,120);if(!name)fail('ระบุชื่อหมวดสินค้า');if(!run('UPDATE categories SET name=? WHERE id=?',name,cm[1]).changes)fail('ไม่พบหมวดสินค้า',404);audit(s.email,'category.updated',cm[1]);send(res,200,{ok:true});return true;}
  const pm=p.match(/^\/api\/admin\/products(?:\/([a-zA-Z0-9-]+))?$/);if(pm&&(m==='POST'||m==='PUT')){const b=await body(req),v=validateProduct(b);const id=pm[1]||'p-'+randomBytes(8).toString('hex');transaction(()=>{if(m==='PUT'){const current=q('SELECT * FROM products WHERE id=?',id);if(!current)fail('ไม่พบสินค้า',404);if(current.version!==b.version)fail('สินค้าถูกแก้ไขแล้ว กรุณาโหลดข้อมูลใหม่',409);run('UPDATE products SET sku=?,name=?,category_id=?,description=?,image=?,price=?,stock=?,active=?,popular=?,version=version+1,updated_at=? WHERE id=?',v.sku,v.name,v.category_id,v.description,v.image,v.price,v.stock,v.active,b.popular===undefined?current.popular:v.popular,now(),id);}else{run('INSERT INTO products(id,sku,name,category_id,description,image,price,stock,active,popular,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)',id,v.sku,v.name,v.category_id,v.description,v.image,v.price,v.stock,v.active,v.popular,now());}audit(s.email,'product.saved',id);});send(res,200,{id});return true;}
  if(p==='/api/admin/quotes'&&m==='GET'){send(res,200,all('SELECT * FROM quotes ORDER BY created_at DESC LIMIT 1000').map(serialize));return true;}
  const qm=p.match(/^\/api\/admin\/quotes\/([A-Z0-9-]+)(?:\/(offer|status|share))?$/);
  if(qm){const id=qm[1],action=qm[2];const row=q('SELECT * FROM quotes WHERE id=?',id);if(!row)fail('ไม่พบรายการ',404);if(m==='GET'&&!action){send(res,200,serialize(row));return true;}if(m==='POST'&&action==='share'){const raw=token();run('UPDATE quotes SET token_hash=? WHERE id=?',hash(raw),id);audit(s.email,'quote.link_rotated',id);send(res,200,{token:raw});return true;}
   if(m==='POST'&&action==='offer'){const b=await body(req);transaction(()=>{const r=q('SELECT * FROM quotes WHERE id=?',id);if(!['pending','offered'].includes(r.status)||r.version!==b.version)fail('สถานะเปลี่ยนแล้ว กรุณาโหลดข้อมูลใหม่',409);const items=JSON.parse(r.items);if(!Array.isArray(b.prices)||b.prices.length!==items.length||!b.prices.every(v=>integer(v)))fail('กรุณากำหนดราคาทุกรายการ');if(!integer(b.shipping))fail('ค่าจัดส่งไม่ถูกต้อง');const expires=Date.parse(b.validUntil);if(!Number.isFinite(expires)||expires<Date.now()||expires>Date.now()+90*86400000)fail('วันหมดอายุต้องอยู่ภายใน 90 วัน');items.forEach((i,n)=>i.unitPrice=b.prices[n]);const total=items.reduce((n,i)=>n+i.qty*i.unitPrice,0)+b.shipping;if(!Number.isSafeInteger(total)||total>10000000000)fail('ยอดรวมสูงเกินไป');run("UPDATE quotes SET items=?,shipping=?,valid_until=?,admin_note=?,status='offered',version=version+1,updated_at=? WHERE id=?",JSON.stringify(items),b.shipping,new Date(expires).toISOString(),text(b.note,3000),now(),id);audit(s.email,'quote.offered',id);});send(res,200,serialize(q('SELECT * FROM quotes WHERE id=?',id)));return true;}
   if(m==='POST'&&action==='status'){const b=await body(req);transaction(()=>{const r=q('SELECT * FROM quotes WHERE id=?',id);if(r.version!==b.version)fail('สถานะเปลี่ยนแล้ว กรุณาโหลดข้อมูลใหม่',409);const allowed={pending:['cancelled'],offered:['cancelled'],confirmed:['processing','cancelled'],processing:['shipped','cancelled'],shipped:['completed'],completed:[],cancelled:[]};if(!allowed[r.status]?.includes(b.status))fail('ไม่สามารถเปลี่ยนสถานะนี้ได้',409);if(b.status==='shipped'&&(!text(b.tracking,150)||!text(b.carrier,100)))fail('กรุณาระบุผู้ขนส่งและเลขพัสดุ');if(b.status==='cancelled'&&['confirmed','processing'].includes(r.status)){for(const i of JSON.parse(r.items))if(i.productId&&i.reserved)run('UPDATE products SET stock=CASE WHEN stock IS NULL THEN NULL ELSE stock+? END,version=version+1,updated_at=? WHERE id=?',i.qty,now(),i.productId);}run('UPDATE quotes SET status=?,tracking=?,carrier=?,version=version+1,updated_at=? WHERE id=?',b.status,text(b.tracking,150)||r.tracking,text(b.carrier,100)||r.carrier,now(),id);audit(s.email,'order.'+b.status,id);});send(res,200,serialize(q('SELECT * FROM quotes WHERE id=?',id)));return true;}
  }
  if(p==='/api/admin/export'&&m==='GET'){send(res,200,{exportedAt:now(),categories:all('SELECT * FROM categories'),products:all('SELECT * FROM products'),quotes:all('SELECT * FROM quotes').map(serialize),events:all('SELECT * FROM events')});return true;}
 }
 fail('ไม่พบข้อมูล',404);
 }catch(e){const status=e.status||((e.message||'').includes('UNIQUE constraint')?409:500);send(res,status,{error:status===500?'เกิดข้อผิดพลาด กรุณาลองใหม่':status===409&&!e.status?'SKU นี้ถูกใช้แล้ว':e.message});if(status===500)console.error('API failure:',e.message);}
 return true;
 }
 return {handle,db,close:()=>db.close()};
}
module.exports={createBackend,passwordHash,hash};
